apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockersampleconfigdepl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: WebApiWithDocker
  template:
    metadata:
      labels:
        app: WebApiWithDocker
    spec:
      containers:
      - name: dnazureeacr
        image: dnazureeacr.azurecr.io/dnazureeacr:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: dsconfigsn1

---
apiVersion: v1
kind: Service
metadata:
  name: webapiwithdocker
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: WebApiWithDocker